### ISSUE TITLE
Running Infer fails for Python 2.7 dependency

### ISSUE THREAD

**Issue by wolf99** [facebook/infer#1251]
I have downloaded and untarred the *v0.17.0* tarball from the GitHub releases page on my *Ubuntu 18.04*.
per the [Quick Start Hello, World ](https://fbinfer.com/docs/hello-world#hello-world-make) page I am running the command `infer run -- make` on a known working makefile in a gcc C project.

I see the output of the C program, then Infer showing progress, then:

```bash
Found 3 source files to analyze in /mnt/c/Users/tobym/git/c/build/acronym/infer-out


Analysis finished in 17.589ss
/usr/bin/env: ‘python2.7’: No such file or directory
** Error running the reporting script:
**   /mnt/c/Users/tobym/git/infer-test/infer-linux64-v0.17.0/lib/infer/infer/bin/../lib/python/report.py --issues-json /mnt/c/Users/tobym/git/c/build/acronym/infer-out/report.json --issues
-txt /mnt/c/Users/tobym/git/c/build/acronym/infer-out/bugs.txt --project-root /mnt/c/Users/tobym/git/c/build/acronym --results-dir /mnt/c/Users/tobym/git/c/build/acronym/infer-out
** See error above
```

I assume this means there are dependencies required outside of the binary that are undocumented.

The documentation does not mention dependencies to run the binary installation, it mentiones dependencies specifically only for building from source. 

Please can you list which dependencies are required to run the binary installation.

PS: Side question; any specific reason to depend on Python 2 rather than 3? Hardly anything that is still under active development still uses 2 any more.

**Comment by XVilka** [comment]
It's fixed in the current master and will be a part of the next release. See https://github.com/facebook/infer/issues/934 for more information/

**Comment by wolf99** [comment]
Can a section be added to mention the dependencies required to _run_ (not build) infer at https://github.com/facebook/infer/blob/master/INSTALL.md ?
My use was stopped by the above error. Now this is solved (great 🙌 ) but I have no info (until I run it again) for if their are other requirements. Any new users will still not know even this requirement.

**Comment by wolf99** [comment]
Also, any info on when the next release would happen? 
The last one was way back in August, there were probably loads of juicy changes since then 😄.
 
I would like to use Infer for a specific CI task so am not massively interested in building it from source on every run, nor in maintaining a separate binary for the CI to avoid building on every run.

**Comment by XVilka** [comment]
@wolf99 looks very soon: https://github.com/facebook/infer/commit/7df439c8143b658224a18dee6af08791413a8a12

**Comment by wolf99** [comment]
Hmmm... 😕 
Unfortunately I don't have time to help out myself either 😞

**Comment by martintrojer** [comment]
Closing — this refers to an unsupported/obsolete toolchain, OS, or Infer release version and is no longer reproducible on a current build. Please reopen (or file a fresh issue) against a current release if you still hit this. Thanks!
